export { default as p01 } from './p01Idly'
export { default as p02 } from './p02Campfire'
export { default as p03 } from './p03Wonderland'
export { default as p04 } from './p04Paragraph'
export { default as p05 } from './p05Superhappy'
export { default as p06 } from './p06Nofie'
