export { default as Main } from './Main'
export { default as Works } from './Works'
export { default as Profile } from './Profile'
export { default as Photolog } from './Photolog'
export { default as Contact } from './Contact'
